server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/my_youtube_app"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
youtube:
  api:
    key: "AIzaSyDSqOHp2sYXjLsWPpc9R7_a-3aJbPSFi8E"
logging:
  level:
    root: INFO
    com.example.MyYoutubePj: DEBUG
